// Client-supplied biographies, Liberia overview and September 26–30 correspondence.
// Publication summaries and provenance are recorded in docs/reviews/2026-10-02/content-structure.md.
export const businesses = [
  {id:'bdavis',name:'BDavis Designs',person:'Brandi Davis-Fitch',country:'United States',location:'Chicago',sector:'Design & apparel',description:'Graphic design, web design and apparel production for entrepreneurs, small businesses and community organisations.',profile:'Brandi Davis-Fitch'},
  {id:'bunnyland',name:'Bunnyland Developmental Child Care Center',person:'Kailyn Harrington · Managing owner',country:'United States',location:'Roseland, Chicago',sector:'Child care',description:'A family-founded early childhood education organisation serving Roseland since 1979, now led by its second generation.',profile:'Kailyn Harrington'},
  {id:'czl',name:'CZL P.C.',person:'Chipo Nyambuya · Co-founder & managing partner',country:'United States',location:'Chicago',sector:'Legal & professional services',description:'A legal and consulting practice represented by Chipo, whose experience connects law, governance and corporate social responsibility.',profile:'Chipo Nyambuya, Esq'},
  {id:'exquisite-catering',name:'Exquisite Catering & Events',person:'Tiffany “Chef Mama” Williams',country:'United States',location:'Chicago',sector:'Food & hospitality',description:'Creative, made-from-scratch catering rooted in Chicago’s South Side, serving events, productions and entertainment clients.',profile:'Tiffany “Chef Mama” Williams'},
  {id:'exquisite-kitchen',name:'Exquisite Kitchen',person:'Tiffany “Chef Mama” Williams',country:'United States',location:'Chicago',sector:'Shared kitchens',description:'A licensed shared commercial kitchen supporting food entrepreneurs with kitchen space, mentorship and operational guidance.',profile:'Tiffany “Chef Mama” Williams'},
  {id:'jennima',name:'Jennima’s Juice',person:'Jennima Merriam',country:'Liberia',location:'Liberia',sector:'Food & beverage',description:'A juice enterprise in WisConnect’s Liberia network, bringing food and beverage entrepreneurship into the cooperative.',profile:null},
  {id:'momentum',name:'Momentum Coffee',person:'Nikki Bravo & Tracy Powell · Co-founders',country:'United States',location:'Chicago',sector:'Coffee & community',description:'A coffee business connecting hospitality, entrepreneurship and community investment, with support for emerging food entrepreneurs.',profile:'Nikki Bravo'},
  {id:'river-cess-agriculture',name:'River Cess Agriculture',person:null,country:'Liberia',location:'River Cess',sector:'Agriculture',description:'Part of the Liberia network’s agricultural enterprise, connecting the cooperative to its focus on local land, knowledge and community opportunity.',profile:null},
  {id:'river-cess-mining',name:'River Cess Mining',person:null,country:'Liberia',location:'River Cess',sector:'Mining',description:'A mining enterprise in the Liberia network, one of the economic sectors included in WisConnect’s community development approach.',profile:null},
  {id:'wisinsup',name:'WisInSup Inc.',person:null,country:'Liberia',location:'Liberia',sector:'Enterprise',description:'Part of WisConnect Liberia’s member-business network. Connect with the cooperative to learn more about its work.',profile:null},
  {id:'zead',name:'ZE’AD Advisors and Consultants',person:'Ade Wede Wee-Wee Kekuleh · Partner',country:'Liberia',location:'Liberia',sector:'Professional services',description:'A professional practice represented in the network by Ade Wede, whose experience spans law, accounting and human rights.',profile:'Ade Wede Wee-Wee Kekuleh'},
].sort((a,b)=>a.name.localeCompare(b.name));
