// Navigation follows the platform phases recorded in WISCONNECT_CONTEXT.md.
// These sections are UI previews; they do not represent connected records.
export const sections = {
  members: { title: "Members", icon: "people", subtitle: "The people behind the cooperative.", description: "Member profiles, membership status and directory visibility will be managed here.", tabs: ["All members", "Active", "Inactive"], columns: ["Member", "Membership", "Location", "Status"], adminOnly: true },
  applications: { title: "Applications", icon: "clipboard", subtitle: "From first interest to membership.", description: "Review membership applications, requested information and approval decisions in one place.", tabs: ["To review", "Approved", "Declined"], columns: ["Applicant", "Submitted", "Reviewer", "Status"], adminOnly: true },
  businesses: { title: "Businesses", icon: "business", subtitle: "Keep member enterprises connected.", description: "Track member-owned businesses, their sectors and the people responsible for them.", tabs: ["All businesses", "Products", "Services"], columns: ["Business", "Member", "Sector", "Status"], adminOnly: true },
  projects: { title: "Projects", icon: "folder", subtitle: "Turn shared plans into progress.", description: "Organize cooperative projects, owners, milestones and supporting documents.", tabs: ["Active", "Planned", "Completed"], columns: ["Project", "Owner", "Next milestone", "Status"], adminOnly: true },
  payments: { title: "Payments & dues", icon: "wallet", subtitle: "Keep a clear record of contributions.", description: "Membership dues, payment records and receipts will appear here when payment tracking is connected.", tabs: ["Records", "Dues", "Receipts"], columns: ["Reference", "Purpose", "Date", "Amount", "Status"], adminOnly: false },
  investments: { title: "Investments", icon: "chart", subtitle: "A clearer view of shared capital.", description: "View cooperative investment information, contributions and statements. No balances are connected yet.", tabs: ["Overview", "Contributions", "Statements"], columns: ["Investment", "Period", "Contribution", "Status"], adminOnly: false },
  reports: { title: "Reports", icon: "chart", subtitle: "Understand the work and its impact.", description: "Explore the cooperative’s financial, sales, membership, activity and impact reporting.", tabs: ["Financial", "Sales", "Membership", "Activity", "Impact"], columns: ["Report", "Period", "Prepared by", "Updated"], adminOnly: true },
  documents: { title: "Documents", icon: "folder", subtitle: "The right information, in one place.", description: "Access cooperative documents, policies, member resources and training materials.", tabs: ["All documents", "Policies", "Forms", "Training"], columns: ["Document", "Category", "Updated", "Access"], adminOnly: false },
  marketplace: { title: "Marketplace", icon: "business", subtitle: "Bring member products to market.", description: "A future catalog of member products and services, with WisConnect coordinating sales on members’ behalf.", tabs: ["Products", "Services", "Categories"], columns: ["Listing", "Business", "Category", "Availability"], adminOnly: false },
  orders: { title: "Orders", icon: "cart", subtitle: "Follow each order from start to finish.", description: "Order details, payment status, shipping and delivery tracking will live here when commerce is connected.", tabs: ["All orders", "Processing", "Shipped", "Completed"], columns: ["Order", "Placed", "Total", "Payment", "Delivery"], adminOnly: false },
  website: { title: "Website content", icon: "updates", subtitle: "Keep the cooperative’s story current.", description: "Organize public pages, news, events and gallery content for review and publication.", tabs: ["Pages", "News", "Events", "Gallery"], columns: ["Title", "Author", "Updated", "Publication"], adminOnly: true },
  team: { title: "Team & permissions", icon: "shield", subtitle: "The right access for each responsibility.", description: "Staff accounts, responsibilities and permission levels will be managed here. Account invitations already work in Invitations.", tabs: ["Staff", "Roles", "Permissions"], columns: ["Staff member", "Role", "Access", "Status"], adminOnly: true },
  membership: { title: "My membership", icon: "people", subtitle: "Your place in the cooperative.", description: "Your membership record, renewal information and cooperative participation will appear here.", tabs: ["Overview", "Renewal", "Participation"], columns: ["Membership", "Period", "Renewal", "Status"], adminOnly: false },
  myBusiness: { title: "My business", icon: "business", subtitle: "A home for your enterprise.", description: "Your business profile, products and services will connect to the cooperative’s business records.", tabs: ["Business profile", "Products", "Services"], columns: ["Business", "Sector", "Contact", "Status"], adminOnly: false },
  training: { title: "Training", icon: "book", subtitle: "Build skills and share knowledge.", description: "Find training materials and learning resources provided by the cooperative.", tabs: ["Materials", "Sessions", "My learning"], columns: ["Resource", "Topic", "Format", "Updated"], adminOnly: false },
  messages: { title: "Messages", icon: "message", subtitle: "Stay connected with other members.", description: "Member-to-member conversations and cooperative messages will appear here once messaging is connected.", tabs: ["Inbox", "Sent"], columns: ["Conversation", "From", "Last update"], adminOnly: false },
  updates: { title: "News & events", icon: "calendar", subtitle: "What’s happening in your cooperative.", description: "Follow cooperative announcements, member stories and upcoming events.", tabs: ["News", "Events", "Member stories"], columns: ["Title", "Category", "Date"], adminOnly: false },
} as const;

export type SectionKey = keyof typeof sections;
export type View = "home" | "account" | "help" | "invitations" | SectionKey;

export const adminItems = ["members", "businesses", "payments", "projects", "documents", "reports"] as const;
export const memberItems = ["membership", "myBusiness", "documents"] as const;
